[package]
name = "zkps"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
num-bigint = "0.4"
num-prime = "0.3"
num-primes = "0.3.0"
num-traits = "0.2.19"
rand = "0.8.4"

# num_traits = "0.1.42"

